version: '2'
services:
  money:
    build: images/python
    links:
      - mysql
      - redis
    environment:
      PROJECT_ROOT: /opt/fat-wallet/backend
    working_dir: /opt/fat-wallet/backend
    volumes:
      - ../..:/opt/fat-wallet
      - ./dev/profile:/root/.bashrc
      - ./dev/web_run:/etc/service/web/run
    ports:
      - 5000:5000
    restart: always
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: money
      MYSQL_ROOT_PASSWORD: admin
  celery:
    build: images/python
# celery -A backend.celery.config:celery beat --config=backend.celery.config --loglev=DEBUG
    command: celery -A backend.celery.config:celery worker --config=backend.celery.config -B
    working_dir: /opt/fat-wallet/backend
    volumes:
      - ../..:/opt/fat-wallet
    environment:
      PYTHONPATH: /opt/fat-wallet
    links:
      - mysql
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always