"""empty message

Revision ID: 00af8fe38878
Revises: ffcf69702320
Create Date: 2019-06-20 10:43:04.914954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00af8fe38878'
down_revision = 'ffcf69702320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(length=20), nullable=True))
    op.drop_column('tasks', 'start_time')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
