"""empty message

Revision ID: 377ba6575c9b
Revises: 2224c5484e16
Create Date: 2019-06-27 02:22:23.484705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '377ba6575c9b'
down_revision = '2224c5484e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('extra', sa.TEXT(), nullable=False))
    op.alter_column('tasks', 'creator_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tasks', 'reward',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tasks', 'task_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tasks', 'reward',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tasks', 'creator_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('tasks', 'extra')
    # ### end Alembic commands ###
