"""add unique constraint

Revision ID: 3ccb22040f9d
Revises: 5794e40a1edd
Create Date: 2019-06-11 02:45:21.283584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ccb22040f9d'
down_revision = '5794e40a1edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_collect_uc', 'collects', ['user_id', 'task_id'])
    op.create_unique_constraint('_participate_uc', 'participates', ['user_id', 'task_id'])
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint('_participate_uc', 'participates', type_='unique')
    op.drop_constraint('_collect_uc', 'collects', type_='unique')
    # ### end Alembic commands ###
