"""empty message

Revision ID: d23975881ec2
Revises: f035a044ea6e
Create Date: 2019-06-30 13:17:13.264799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23975881ec2'
down_revision = 'f035a044ea6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('msg_type', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('send_from', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'send_from')
    op.drop_column('messages', 'msg_type')
    op.drop_column('messages', 'is_used')
    # ### end Alembic commands ###
