"""add unique constraint

Revision ID: d50cf5ae7f15
Revises: 5794e40a1edd
Create Date: 2019-06-10 13:09:44.187392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd50cf5ae7f15'
down_revision = '5794e40a1edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_collect_uc', 'collects', ['user_id', 'task_id'])
    op.create_unique_constraint('_participate_uc', 'participates', ['user_id', 'task_id'])
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'student_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint('_participate_uc', 'participates', type_='unique')
    op.drop_constraint('_collect_uc', 'collects', type_='unique')
    # ### end Alembic commands ###
