"""test

Revision ID: d92c33ef4863
Revises: 70494072915a
Create Date: 2019-06-12 11:02:59.234418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92c33ef4863'
down_revision = '70494072915a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('max_participate', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'start_time')
    op.drop_column('tasks', 'max_participate')
    op.drop_column('tasks', 'due_time')
    # ### end Alembic commands ###
